###Register
POST http://localhost:8081/auth/register
Content-Type: application/json

{
    "name":"strelcock",
    "email": "a@ba.ru",
    "password": "qweasdzxc"
}

###Login
POST http://localhost:8081/auth/login HTTP/1.1
Content-Type: application/json


{
    "email":"a@b.ru",
    "password":"qweasdzxc"
}


###Create Task
POST http://localhost:8081/tasks/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYmEucnUiLCJpZCI6M30.24HtOF0WP3GJ8Ez_mQIPlO_5m3vsYXw1yks7yhnT2r8

{
    "name":"Task 5"
}


###Get Tasks || query: show=all;done;task_name
GET http://localhost:8081/tasks/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYmEucnUiLCJpZCI6M30.24HtOF0WP3GJ8Ez_mQIPlO_5m3vsYXw1yks7yhnT2r8


###Do task
PATCH http://localhost:8081/tasks/mark/Task+1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYmEucnUiLCJpZCI6MX0.eT5PdeQMgwj5YSE1CJCvd0SCw3dF6L_-CKrHSDeTBM4

{
    "status": true
}

###Change TAsk Name
PATCH http://localhost:8081/tasks/name/Buy+bread
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYmEucnUiLCJpZCI6MX0.eT5PdeQMgwj5YSE1CJCvd0SCw3dF6L_-CKrHSDeTBM4

{
    "new_name":"    UI"
}


###Delete task
DELETE http://localhost:8081/tasks/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYmEucnUiLCJpZCI6MX0.eT5PdeQMgwj5YSE1CJCvd0SCw3dF6L_-CKrHSDeTBM4

{
    "name":"UI"
}


###DElete USer 
DELETE http://localhost:8081/user/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYi5ydSIsImlkIjoyfQ.RzEfEgxUFr9hjQYQnABboIBBqBJ7Eku31IsPNocVUzk

{
    "email":"a@b.ru"
}

###Change USer name
PATCH http://localhost:8081/user/name
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYmEucnUiLCJpZCI6MX0.eT5PdeQMgwj5YSE1CJCvd0SCw3dF6L_-CKrHSDeTBM4

{
    "new_name":"GRECHA LOH",
    "email":"a@ba.ru"
}

